# Generated by Django 4.2 on 2023-04-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='trending',
        ),
    ]
